---
# React Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  replicas: 4
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: gouthamc125/weatherapp:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe: 
          httpGet: 
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
            
---
# Weather Application Service
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: weatherapp
