#Weatherapp Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: gouthamc125/weatherapp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
#Weatherapp Service
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-svc
spec:
  type: LoadBalancer
  selector:
    app: weatherapp
  ports:
  - port: 80
    targetPort: 80

